export interface MenuTableData {
  resourceCode?: string
  createdTime?: string
  createdBy?: string
  describe?: string
  id?: number
  menuId?: number
  method?: string
  resourceName?: string
  updatedTime?: string
  updatedBy?: string
  url?: string
}
// Generated by https://quicktype.io

// 用户翻页
export interface PageListEntity {
  total?: string
  size?: string
  pages?: string
  page?: string
  current?: string
  list?: MenuTableData[]
}
